Repository NASA-Planetary-Science/sbpy, pull requests merged in 2023-06, with the labels that each got.

#367 Enable combining `DataClass` objects
  CHANGES.rst
  docs/sbpy/data/dataclass.rst
  sbpy/data/core.py
  sbpy/data/tests/test_dataclass.py
Labels: enhancement, data

#371 Add CALSPEC model solar spectrum
  docs/sbpy/calib.rst
  sbpy/calib/solar_sources.py
  sbpy/calib/tests/test_sun.py
Labels: calibration

#379 Avoid a dirty git index with readthedocs
  .gitignore
  .readthedocs.yaml
Labels: documentation
